default:
  image: registry.gitlab.com/prilus/mabidilmeter/buildimage

build:
  stage: build
  script:
    # front build
    - cd front
    - npm install && npm run build
    - cp -r dist/* ../cmd/dilmeterapi/static
    - cd ..
    # api build
    - GOOS=windows GOARCH=amd64 go build  -ldflags="-s -w" -trimpath -o dilmeterapi.exe ./cmd/dilmeterapi
    - GOOS=windows GOARCH=386 go build  -ldflags="-s -w" -trimpath -o dilmeterapi_x86.exe ./cmd/dilmeterapi
    - zip -e -P $ZIP_PASSWORD dilmeterapi.zip dilmeterapi.exe dilmeterapi_x86.exe
    # upload artifact to release
    - export DATESTR=$(date +"%Y%m%d-%H%M%S")
    - export RELEASE_FILENAME=dilmeterapi-$DATESTR-${CI_COMMIT_SHA}.zip
    - 'wget --header "JOB-TOKEN: $CI_JOB_TOKEN" --method PUT --body-file dilmeterapi.zip "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/dilmeterapi/0.0.1/$RELEASE_FILENAME"'
  artifacts:
    paths:
      - dilmeterapi.zip
    expire_in: 30 days
