import type { eventBardsong } from '@/protocols';
import type { EntityConditionState } from '@/eventActor';

// Synthetic CCId, not a real one — real CCIds top out at 10138, so
// 900000 + song id 206 stays clear of a bump.
//
// Its icon (public/icons/cc/900206.png) is generated by build-data.mjs from
// skill 10003 (SYNTHETIC_CC_ICONS there). That build step only guards a
// missing skill file; it can't catch this id itself drifting out of sync
// with SYNTHETIC_CC_ICONS's ccId — bardsongTrack.test.ts checks that instead.
export const BARDSONG_CC_ID = 900206;

// Folds eventBardsong start/end events into a synthetic CC history by depth
// count, not pairing: unmatched ends are absorbed (depth floors at 0), and an
// overlapping start does not reset the run's already-open start time.
//
// Events are assumed already sorted by At (they are pushed in arrival order).
export function buildBardsongConditionHistory(events: eventBardsong[]): EntityConditionState[] {
    const out: EntityConditionState[] = [];
    let depth = 0;
    let present = false;

    for (const e of events) {
        depth = e.IsEnd ? Math.max(0, depth - 1) : depth + 1;
        const nowPresent = depth > 0;
        if (nowPresent === present) continue; // depth changed but presence did not

        present = nowPresent;
        out.push({
            At: e.At,
            // Unlike a real EntityCondition.At (bumped on every re-enable), this
            // At is fixed to when the run started and is never refreshed.
            List: present
                ? [{ Id: '', At: e.At, CCId: BARDSONG_CC_ID, DisableAt: 0, AttackerId: '', Params: {} }]
                : [],
        });
    }

    return out;
}
