import type { eventBardsong } from '@/protocols';
import type { EntityConditionState } from '@/eventActor';

// Synthetic CCId, not a real one — real CCIds top out at 10138, so
// 900000 + song id 206 stays clear of a bump.
//
// Its icon (public/icons/cc/900206.png) is generated by build-data.mjs from
// skill 10003 (SYNTHETIC_CC_ICONS there). That build step only guards a
// missing skill file; it can't catch this id itself drifting out of sync
// with SYNTHETIC_CC_ICONS's ccId — bardsongTrack.test.ts checks that instead.
export const BARDSONG_CC_ID = 900206;

// Folds eventBardsong start/end events into a synthetic CC history. The
// buff is a single non-stacking state: a start turns it on (a repeated
// start only refreshes — the game re-announces every re-shout and the
// server sometimes double-sends), a single end turns it off. Depth
// counting is wrong here: starts are not balanced by ends, and one stray
// duplicate kept the lane on for the rest of the fight (coverage 100%).
//
// An orphan start whose end notice never arrives (player dead or out of
// range when the effect lapsed) auto-expires BARDSONG_MAX_SEC after the
// last refresh — the effect refreshes announcements often enough that
// 20s of silence means it is gone.
//
// Events are assumed already sorted by At (they are pushed in arrival order).
export const BARDSONG_MAX_SEC = 20;

export function buildBardsongConditionHistory(events: eventBardsong[]): EntityConditionState[] {
    const out: EntityConditionState[] = [];
    let present = false;
    let runStart = 0;
    let lastRefresh = 0;

    const off = (at: number) => {
        out.push({ At: at, List: [] });
        present = false;
    };

    for (const e of events) {
        if (present && e.At > lastRefresh + BARDSONG_MAX_SEC) {
            off(lastRefresh + BARDSONG_MAX_SEC);
        }
        if (e.IsEnd) {
            if (present) off(e.At);
            continue;
        }
        lastRefresh = e.At;
        if (!present) {
            present = true;
            runStart = e.At;
            out.push({
                At: e.At,
                // Unlike a real EntityCondition.At (bumped on every re-enable),
                // this At is fixed to when the run started, never refreshed.
                List: [{ Id: '', At: runStart, CCId: BARDSONG_CC_ID, DisableAt: 0, AttackerId: '', Params: {} }],
            });
        }
    }
    if (present) {
        // Live rebuilds replace this synthetic tail once a real end arrives.
        off(lastRefresh + BARDSONG_MAX_SEC);
    }

    return out;
}
